### PR TITLE
Update zipcodes db

### PR DESCRIPTION
**Pull request by TJBANEY**
This updates zips.json to one retrieved on August of 2020.

### CODE REVIEW

**Comment by seanpianka** [comment]
Hi @TJBANEY and thanks for the PR. I'm hesitant to merge this update since users have experienced reliability issues in the past, see #3 and #4. I patched this by combining data from [1] and [2], specifically merging the longitude/latitude data from [2] into [1], then converting [1] into a format more accessible/performant from code. 

I filed #7 as a way to track the work of automating this multi-step data reliability changes, but I haven't gotten time to figure the rest of it out. The scripts to perform this reliability update are located under `/ci/data`, and if your PR could include these modifications, I could approve and merge this.

**Comment by sierraone** [comment]
Commenting here as I'm interested in updating the dataset (as well as for my own use). How did you extract the geocodes for source [2]? @seanpianka

**Comment by seanpianka** [comment]
I invoke [this file [0]](https://github.com/seanpianka/Zipcodes/blob/master/ci/__init__.py#L13) directly and it loads the data from [ci/data](https://github.com/seanpianka/Zipcodes/tree/master/ci/data) and combines them both into the final dataset that is used by the library.

[0] defines a dict that holds the "schema" the JSON returned by library (query) calls. The dict's keys are the field name from the transformed dataset, and the value is a dict that contains the "public" field name in this library's API, along with an optional pre-processing function for the transformation.

As mentioned above, the data comes from two different datasources. We need to download the recent versions of those, place them with the same final names into `ci/data`, and run the script. Once that's done, I can release a new version.

**Comment by seanpianka** [comment]
I merged the original dataset with more accurate geolocation data from 2019 into a download of the main [1] zipcode dataset  from 3 Oct. 2021. It was merged by running the dataset generation script:

```bash
$ python scripts/build_zipcode_dataset.py
("GPS Keys: ['ZipCode', 'City', 'State', 'Latitude', 'Longitude', "
 "'Classification', 'Population']")
("Base Keys: ['zip', 'type', 'decommissioned', 'primary_city', "
 "'acceptable_cities', 'unacceptable_cities', 'state', 'county', 'timezone', "
 "'area_codes', 'world_region', 'country', 'latitude', 'longitude', "
 "'irs_estimated_population']")
Updated GPS from GPS CSV in 0.026109933853149414 seconds.
Writing zipcode information for 42724 places
To zip for production, run:
$ bzip2 zips.json
```

This has been released as a 1.2.0.

**Pull request closed without merging**
